### PR TITLE
warn if no PosixAPI available (rather than NPE)

### PR DESCRIPTION
**Pull request by JerryShea**

### CODE REVIEW

**Comment by peter-lawrey** [comment]
The warning should be a once off

**Comment by JerryShea** [comment]
> The warning should be a once off

well then maybe we don't warn at all and rely on https://github.com/OpenHFT/Posix/pull/21 instead - what do you think?

**Comment by peter-lawrey** [comment]
The psox should return a dummy implementation that either does nothing or always returns an appropriate error

**Comment by JerryShea** [comment]
Replaced by https://github.com/OpenHFT/Posix/pull/21/

**Pull request closed without merging**
