### PR TITLE
Change RandomDataInput.copyTo(ByteBuffer) to copy from readingPosition

### PR DESCRIPTION
**Pull request by gortiz**
See #478

### CODE REVIEW

**Review by peter-lawrey — APPROVED** [review]

**Comment by JerryShea** [comment]
@gortiz could we ask that you sign the https://chronicle.software/contributor-agreement/ please? Thanks!

**Comment by gortiz** [comment]
Done

**Comment by gortiz** [comment]
Btw, I gave up on trying to use chronicle bytes in Pinot given that I've found several errors like this and my PRs weren't reviewed. In case you have time to review them I may try to find some way to continue with that project

**Comment by JerryShea** [comment]
Thanks for signing the CLA. 
Sorry about not reviewing the PRs - we were busy with customer work; which is a just an excuse I know.... 
We will keep an eye out for your PRs if/when you come back!

**Comment by alamar** [comment]
Released in Chronicle-Bytes `2.24ea7`, Chronicle-BOM `2.24ea47`

**Pull request merged**
